### ISSUE TITLE
go build fails on Ubuntu

### ISSUE THREAD

**Issue by depeele** [mkilling/goejdb#4]
I'm trying to build on Ubuntu (Linux precise64 3.2.0-23-generic) and I get the following errors:
```
# github.com/mkilling/goejdb
./ejcoll.go:37: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbsavebson
./ejcoll.go:69: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbrmbson
./ejcoll.go:77: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbloadbson
./ejcoll.go:131: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbupdate
./ejcoll.go:162: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbsetindex
./ejcoll.go:171: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbtranbegin
./ejcoll.go:180: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbtrancommit
./ejcoll.go:189: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbtranabort
./ejcoll.go:199: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbtranstatus
./ejcoll.go:205: cannot use coll.ptr (type *[0]byte) as type *C.struct_EJCOLL in argument to _Cfunc_ejdbsyncoll
./ejcoll.go:205: too many errors
```

I'm using the latest version of ejdb:
```
git clone git@github.com:Softmotions/ejdb.git
cd ejdb
make
sudo make -C ./tcejdb install
```

Are these go bindings supposed to work with the latest ejdb?
Am I missing something obvious?

Thanks for any help you can provide!

**Comment by mkilling** [comment]
Hi, I haven't tested the bindings with the latest ejdb version. Unfortunately I won't have time to look at this atm - if you find out anything please submit a pull request or post in this issue. Sorry!

**Comment by depeele** [comment]
Looks like these bindings only work with go-1.2.2 (fails in the same way with go-1.3.3).

Looks like the "proper use" of cgo changed between 1.2.2 and 1.3 ...

I wish I were more knowledgeable about the use of cgo...

**Comment by depeele** [comment]
From the [go-1.3 release notes](https://golang.org/doc/go1.3#cgo):
> The cmd/cgo command, which processes import "C" declarations in Go packages, has corrected a serious bug that may cause some packages to stop compiling. Previously, all pointers to incomplete struct types translated to the Go type *[0]byte, with the effect that the Go compiler could not diagnose passing one kind of struct pointer to a function expecting another. Go 1.3 corrects this mistake by translating each different incomplete struct to a different named type.
> 
> Given the C declaration typedef struct S T for an incomplete struct S, some Go code used this bug to refer to the types C.struct_S and C.T interchangeably. Cgo now explicitly allows this use, even for completed struct types. However, some Go code also used this bug to pass (for example) a *C.FILE from one package to another. This is not legal and no longer works: in general Go packages should avoid exposing C types and names in their APIs.
> 
> Updating: Code confusing pointers to incomplete types or passing them across package boundaries will no longer compile and must be rewritten. If the conversion is correct and must be preserved, use an explicit conversion via unsafe.Pointer.

**Comment by mkilling** [comment]
Thanks for finding this out. If you want to try yourself, I'm happy to accept a pull request. I can't promise I can take care of this myself right now but it sounds like a rather trivial fix.

**Comment by brunetto** [comment]
Does anything changed? I can't still compile it too.. I tried to fix it myself but I have not enough experience with cgo. Maybe with some help I can do that.
Moreover, the name of the imported library changed from `tcejdb` to `ejdb`, at least in the Ubuntu installation from repository (but I was able to fix that)

**Comment by keans** [comment]
Hi, I am not an expert on cgo, but I managed to make it build again. The test seems to be running fine on Debian Jessie as well as MacOSX Yosemite. Please check my pull request.
